# Site settings
name: Devin Henderson
email: HendersonDevin352@gmail.com
#canonical_url: 
keywords: "Director, Chamber of Commerce, administration, javascript, web development"
skills: "Director of Operations, Eureka Springs Chamber of Commerce"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: 
  - title: facebook
    url: https://www.facebook.com/DevinOfEurekaSprings
  - title: 
    url: 

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
